# Welcome to the Interactive Python Tutorial.
# Start by choosing a chapter and
# write your code in this window.

str = """
    item_blink
    item_blades_of_attack
    item_broadsword
    item_chainmail
    item_claymore
    item_helm_of_iron_will
    item_javelin
    item_mithril_hammer
    item_platemail
    item_quarterstaff
    item_quelling_blade
    item_ring_of_protection
    item_stout_shield
    item_recipe_moon_shard
    item_moon_shard
    item_gauntlets
    item_slippers
    item_mantle
    item_branches
    item_belt_of_strength
    item_boots_of_elves
    item_robe
    item_circlet
    item_ogre_axe
    item_blade_of_alacrity
    item_staff_of_wizardry
    item_ultimate_orb
    item_gloves
    item_lifesteal
    item_ring_of_regen
    item_sobi_mask
    item_boots
    item_gem
    item_cloak
    item_talisman_of_evasion
    item_cheese
    item_magic_stick
    item_recipe_magic_wand
    item_magic_wand
    item_ghost
    item_clarity
    item_enchanted_mango
    item_flask
    item_dust
    item_bottle
    item_ward_observer
    item_ward_sentry
    item_recipe_ward_dispenser
    item_ward_dispenser
    item_tango
    item_tango_single
    item_courier
    item_tpscroll
    item_recipe_travel_boots
    item_recipe_travel_boots_2
    item_travel_boots
    item_travel_boots_2
    item_recipe_phase_boots
    item_phase_boots
    item_demon_edge
    item_eagle
    item_reaver
    item_relic
    item_hyperstone
    item_ring_of_health
    item_void_stone
    item_mystic_staff
    item_energy_booster
    item_point_booster
    item_vitality_booster
    item_recipe_power_treads
    item_power_treads
    item_recipe_hand_of_midas
    item_hand_of_midas
    item_recipe_oblivion_staff
    item_oblivion_staff
    item_recipe_pers
    item_pers
    item_recipe_poor_mans_shield
    item_poor_mans_shield
    item_recipe_bracer
    item_bracer
    item_recipe_wraith_band
    item_wraith_band
    item_recipe_null_talisman
    item_null_talisman
    item_recipe_mekansm
    item_mekansm
    item_recipe_vladmir
    item_vladmir
    item_flying_courier
    item_recipe_buckler
    item_buckler
    item_recipe_ring_of_basilius
    item_ring_of_basilius
    item_recipe_pipe
    item_pipe
    item_recipe_urn_of_shadows
    item_urn_of_shadows
    item_recipe_headdress
    item_headdress
    item_recipe_sheepstick
    item_sheepstick
    item_recipe_orchid
    item_orchid
    item_recipe_cyclone
    item_cyclone
    item_recipe_force_staff
    item_force_staff
    item_recipe_dagon
    item_dagon
    item_recipe_necronomicon
    item_necronomicon
    item_recipe_ultimate_scepter
    item_ultimate_scepter
    item_recipe_refresher
    item_refresher
    item_recipe_assault
    item_assault
    item_recipe_heart
    item_heart
    item_recipe_black_king_bar
    item_black_king_bar
    item_aegis
    item_recipe_shivas_guard
    item_shivas_guard
    item_recipe_bloodstone
    item_bloodstone
    item_recipe_sphere
    item_sphere
    item_recipe_lotus_orb
    item_lotus_orb
    item_recipe_vanguard
    item_vanguard
    item_recipe_crimson_guard
    item_crimson_guard
    item_recipe_blade_mail
    item_blade_mail
    item_recipe_soul_booster
    item_soul_booster
    item_recipe_hood_of_defiance
    item_hood_of_defiance
    item_recipe_rapier
    item_rapier
    item_recipe_monkey_king_bar
    item_monkey_king_bar
    item_recipe_radiance
    item_radiance
    item_recipe_butterfly
    item_butterfly
    item_recipe_greater_crit
    item_greater_crit
    item_recipe_basher
    item_basher
    item_recipe_bfury
    item_bfury
    item_recipe_manta
    item_manta
    item_recipe_lesser_crit
    item_lesser_crit
    item_recipe_armlet
    item_armlet
    item_recipe_invis_sword
    item_invis_sword
    item_recipe_silver_edge
    item_silver_edge
    item_recipe_sange_and_yasha
    item_sange_and_yasha
    item_recipe_satanic
    item_satanic
    item_recipe_mjollnir
    item_mjollnir
    item_recipe_skadi
    item_skadi
    item_recipe_sange
    item_sange
    item_recipe_helm_of_the_dominator
    item_helm_of_the_dominator
    item_recipe_maelstrom
    item_maelstrom
    item_recipe_desolator
    item_desolator
    item_recipe_yasha
    item_yasha
    item_recipe_mask_of_madness
    item_mask_of_madness
    item_recipe_diffusal_blade
    item_diffusal_blade
    item_recipe_ethereal_blade
    item_ethereal_blade
    item_recipe_soul_ring
    item_soul_ring
    item_recipe_arcane_boots
    item_arcane_boots
    item_recipe_octarine_core
    item_octarine_core
    item_orb_of_venom
    item_recipe_ancient_janggo
    item_ancient_janggo
    item_recipe_medallion_of_courage
    item_medallion_of_courage
    item_recipe_solar_crest
    item_solar_crest
    item_smoke_of_deceit
    item_recipe_veil_of_discord
    item_veil_of_discord
    item_recipe_guardian_greaves
    item_guardian_greaves
    item_recipe_rod_of_atos
    item_rod_of_atos
    item_recipe_abyssal_blade
    item_abyssal_blade
    item_recipe_heavens_halberd
    item_heavens_halberd
    item_recipe_ring_of_aquila
    item_ring_of_aquila
    item_recipe_tranquil_boots
    item_tranquil_boots
    item_shadow_amulet
    item_recipe_glimmer_cape
    item_glimmer_cape
    item_halloween_candy_corn
    item_mystery_hook
    item_mystery_arrow
    item_mystery_missile
    item_mystery_toss
    item_mystery_vacuum
    item_halloween_rapier
    item_greevil_whistle
    item_greevil_whistle_toggle
    item_present
    item_winter_stocking
    item_winter_skates
    item_winter_cake
    item_winter_cookie
    item_winter_coco
    item_winter_ham
    item_winter_kringle
    item_winter_mushroom
    item_winter_greevil_treat
    item_winter_greevil_garbage
    item_winter_greevil_chewy
"""

i = 0
while i < len(str):
    if str[i] == ' ' and str[i+1] == 'i':
        str = str[:i+1] + "\"" + str[i+1:]
        i = i+2
    elif str[i] == '\n':
        str = str[:i] + "\"\n    {\n        \"ItemPurchasable\"   \"0\"\n    }\n" + str[i:]
        i = i+50
    else:
    	i = i+1
    
print str